### ISSUE TITLE
data

### ISSUE THREAD

**Issue by mzy12345678** [nulledge/bilinear#1]
Thank you for your code. How can I get the data set？

**Comment by nulledge** [comment]
You can download [Human3.6M](http://vision.imar.ro/human3.6m/description.php) and [MPII](http://human-pose.mpi-inf.mpg.de/) dataset separately.

**Comment by mzy12345678** [comment]
@nulledge 
Thank you for your reply. I can't apply for the official account of human36m. Can you tell me the directory form of the data? Thank you
